jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create CodeDeploy deployment
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'  # Updated to your region
          application-name: 'my-application'
          deployment-group: 'my-deployment-group'
          deployment-config: 'CodeDeployDefault.AllAtOnce'
