- name: Trigger deployment
  uses: aws-actions/aws-codedeploy-deploy@v1
  with:
    application-name: 'my-web-app'
    deployment-group: 'prod-group'
    deployment-config-name: CodeDeployDefault.AllAtOnce
    revision-location: |
      {
        "revisionType": "S3",
        "s3Location": {
          "bucket": "${{ secrets.S3_BUCKET }}",
          "key": "app.zip",
          "bundleType": "zip"
        }
      }
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ap-south-1
